# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config  -id {Synth 8-614}  -string {{WARNING: [Synth 8-614] signal 'valor' is read in the process but is not in the sensitivity list [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote.vhd:13]}}  -suppress 
set_msg_config  -id {Synth 8-285}  -string {{ERROR: [Synth 8-285] failed synthesizing module 'Antirrebote_v2' [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote_v2.vhd:10]}}  -suppress 
set_msg_config  -id {Vivado_Tcl 4-5}  -string {{ERROR: [Vivado_Tcl 4-5] Elaboration failed - please see the console for details}}  -suppress 
set_msg_config  -id {Synth 8-3522}  -string {{ERROR: [Synth 8-3522] signal 'copia_input' is already used in the current clocking condition [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote_v2.vhd:22]}}  -suppress 
set_msg_config  -id {Synth 8-614}  -string {{WARNING: [Synth 8-614] signal 'copia_input' is read in the process but is not in the sensitivity list [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote_v2.vhd:14]}}  -suppress 
set_msg_config  -id {Synth 8-27}  -string {{ERROR: [Synth 8-27] else clause after check for clock not supported [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote_v2.vhd:31]}}  -suppress 
set_msg_config  -id {Synth 8-285}  -string {{ERROR: [Synth 8-285] failed synthesizing module 'Arrebote' [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Arrebote.vhd:10]}}  -suppress 
set_msg_config  -id {Synth 8-26}  -string {{ERROR: [Synth 8-26] attribute 'event not implemented [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Arrebote.vhd:29]}}  -suppress 
set_msg_config  -id {Synth 8-27}  -string {{ERROR: [Synth 8-27] else clause after check for clock not supported [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Arrebote.vhd:30]}}  -suppress 
set_msg_config  -id {Synth 8-26}  -string {{ERROR: [Synth 8-26] attribute 'event not implemented [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Arrebote.vhd:20]}}  -suppress 
set_msg_config  -id {Project 1-19}  -string {{CRITICAL WARNING: [Project 1-19] Could not find the file 'C:/Xilinx_clase/Lab1/Lab1.srcs/sim_1/new/tb_LFSR.vhd'.}}  -suppress 
set_msg_config  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'output_reg' [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote.vhd:19]}}  -suppress 
set_msg_config  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'valor_reg' [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote.vhd:22]}}  -suppress 
set_msg_config  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'c_reg' [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote.vhd:20]}}  -suppress 
set_msg_config  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design antirrebote has unconnected port clk}}  -suppress 
set_msg_config  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (valor_reg) is unused and will be removed from module antirrebote.}}  -suppress 
set_msg_config  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (c_reg[31]) is unused and will be removed from module antirrebote.}}  -suppress 
set_msg_config  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraints selected for write.
Resolution: This message can indicate that there are no constraints for the design, or it can indicate that the used_in flags are set such that the constraints are ignored. This later case is used when running synth_design to not write synthesis constraints to the resulting checkpoint. Instead, project constraints are read when the synthesized design is opened.}}  -suppress 
set_msg_config  -id {Synth 8-27}  -string {{ERROR: [Synth 8-27] else clause after check for clock not supported [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote_v2.vhd:27]}}  -suppress 

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_param chipscope.maxJobs 1
  open_checkpoint freq_divider_routed.dcp
  set_property webtalk.parent_dir C:/Xilinx_clase/Lab1/Lab1.cache/wt [current_project]
  catch { write_mem_info -force freq_divider.mmi }
  write_bitstream -force freq_divider.bit 
  catch {write_debug_probes -quiet -force freq_divider}
  catch {file copy -force freq_divider.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

