# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {Synth 8-614}  -string {{WARNING: [Synth 8-614] signal 'valor' is read in the process but is not in the sensitivity list [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote.vhd:13]}}  -suppress 
set_msg_config  -id {Synth 8-285}  -string {{ERROR: [Synth 8-285] failed synthesizing module 'Antirrebote_v2' [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote_v2.vhd:10]}}  -suppress 
set_msg_config  -id {Vivado_Tcl 4-5}  -string {{ERROR: [Vivado_Tcl 4-5] Elaboration failed - please see the console for details}}  -suppress 
set_msg_config  -id {Synth 8-3522}  -string {{ERROR: [Synth 8-3522] signal 'copia_input' is already used in the current clocking condition [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote_v2.vhd:22]}}  -suppress 
set_msg_config  -id {Synth 8-614}  -string {{WARNING: [Synth 8-614] signal 'copia_input' is read in the process but is not in the sensitivity list [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote_v2.vhd:14]}}  -suppress 
set_msg_config  -id {Synth 8-27}  -string {{ERROR: [Synth 8-27] else clause after check for clock not supported [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote_v2.vhd:31]}}  -suppress 
set_msg_config  -id {Synth 8-285}  -string {{ERROR: [Synth 8-285] failed synthesizing module 'Arrebote' [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Arrebote.vhd:10]}}  -suppress 
set_msg_config  -id {Synth 8-26}  -string {{ERROR: [Synth 8-26] attribute 'event not implemented [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Arrebote.vhd:29]}}  -suppress 
set_msg_config  -id {Synth 8-27}  -string {{ERROR: [Synth 8-27] else clause after check for clock not supported [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Arrebote.vhd:30]}}  -suppress 
set_msg_config  -id {Synth 8-26}  -string {{ERROR: [Synth 8-26] attribute 'event not implemented [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Arrebote.vhd:20]}}  -suppress 
set_msg_config  -id {Project 1-19}  -string {{CRITICAL WARNING: [Project 1-19] Could not find the file 'C:/Xilinx_clase/Lab1/Lab1.srcs/sim_1/new/tb_LFSR.vhd'.}}  -suppress 
set_msg_config  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'output_reg' [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote.vhd:19]}}  -suppress 
set_msg_config  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'valor_reg' [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote.vhd:22]}}  -suppress 
set_msg_config  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'c_reg' [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote.vhd:20]}}  -suppress 
set_msg_config  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design antirrebote has unconnected port clk}}  -suppress 
set_msg_config  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (valor_reg) is unused and will be removed from module antirrebote.}}  -suppress 
set_msg_config  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (c_reg[31]) is unused and will be removed from module antirrebote.}}  -suppress 
set_msg_config  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraints selected for write.
Resolution: This message can indicate that there are no constraints for the design, or it can indicate that the used_in flags are set such that the constraints are ignored. This later case is used when running synth_design to not write synthesis constraints to the resulting checkpoint. Instead, project constraints are read when the synthesized design is opened.}}  -suppress 
set_msg_config  -id {Synth 8-27}  -string {{ERROR: [Synth 8-27] else clause after check for clock not supported [C:/Xilinx_clase/Lab1/Lab1.srcs/sources_1/new/Antirrebote_v2.vhd:27]}}  -suppress 

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param chipscope.maxJobs 1
  set_param synth.incrementalSynthesisCache C:/Users/pc/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-7836-DESKTOP-3K9NM8F/incrSyn
  create_project -in_memory -part xc7z020clg484-1
  set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir C:/Xilinx_clase/Lab1/Lab1.cache/wt [current_project]
  set_property parent.project_path C:/Xilinx_clase/Lab1/Lab1.xpr [current_project]
  set_property ip_output_repo C:/Xilinx_clase/Lab1/Lab1.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  add_files -quiet C:/Xilinx_clase/Lab1/Lab1.runs/synth_1/pwm_8.dcp
  link_design -top pwm_8 -part xc7z020clg484-1
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force pwm_8_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file pwm_8_drc_opted.rpt -pb pwm_8_drc_opted.pb -rpx pwm_8_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force pwm_8_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file pwm_8_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file pwm_8_utilization_placed.rpt -pb pwm_8_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file pwm_8_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force pwm_8_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file pwm_8_drc_routed.rpt -pb pwm_8_drc_routed.pb -rpx pwm_8_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file pwm_8_methodology_drc_routed.rpt -pb pwm_8_methodology_drc_routed.pb -rpx pwm_8_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file pwm_8_power_routed.rpt -pb pwm_8_power_summary_routed.pb -rpx pwm_8_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file pwm_8_route_status.rpt -pb pwm_8_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file pwm_8_timing_summary_routed.rpt -pb pwm_8_timing_summary_routed.pb -rpx pwm_8_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file pwm_8_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file pwm_8_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file pwm_8_bus_skew_routed.rpt -pb pwm_8_bus_skew_routed.pb -rpx pwm_8_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force pwm_8_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

